const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const merjs_dep = b.dependency("merjs", .{});
    const mer_mod = merjs_dep.module("mer");
    const runtime_mod = merjs_dep.module("runtime");

    // Routes module (generated by nuri)
    const routes_mod = b.createModule(.{
        .root_source_file = b.path("src/generated/routes.zig"),
    });
    routes_mod.addImport("mer", mer_mod);

    // Layout module (optional, generated by nuri)
    const layout_mod: ?*std.Build.Module = blk: {
        _ = std.Io.Dir.cwd().statFile(b.graph.io, "src/app/layout.zig", .{}) catch break :blk null;
        const m = b.createModule(.{ .root_source_file = b.path("src/app/layout.zig") });
        m.addImport("mer", mer_mod);
        routes_mod.addImport("app/layout", m);
        break :blk m;
    };

    // Wire up each page module in src/app/
    var app_dir = std.Io.Dir.cwd().openDir(b.graph.io, "src/app", .{ .iterate = true }) catch {
        std.debug.print("nuri: no src/app/ directory found — run 'nuri build' first.\n", .{});
        return;
    };
    defer app_dir.close(b.graph.io);

    var walker = app_dir.walk(b.allocator) catch return;
    defer walker.deinit();
    while (walker.next(b.graph.io) catch null) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.path, ".zig")) continue;
        if (std.mem.eql(u8, entry.path, "layout.zig")) continue;

        const file_path = b.fmt("src/app/{s}", .{entry.path});
        const import_name = b.fmt("app/{s}", .{entry.path[0 .. entry.path.len - 4]});

        const page_mod = b.createModule(.{ .root_source_file = b.path(file_path) });
        page_mod.addImport("mer", mer_mod);
        if (layout_mod) |lm| page_mod.addImport("app/layout", lm);
        routes_mod.addImport(import_name, page_mod);
    }

    // Native executable
    const main_mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    main_mod.addImport("mer", mer_mod);
    main_mod.addImport("runtime", runtime_mod);
    main_mod.addImport("routes", routes_mod);
    
    const exe = b.addExecutable(.{ .name = "nuri-site", .root_module = main_mod });
    b.installArtifact(exe);

    // zig build serve - Start dev server
    const run_exe = b.addRunArtifact(exe);
    run_exe.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_exe.addArgs(args);
    b.step("serve", "Start the dev server").dependOn(&run_exe.step);

    // zig build worker - Compile to WASM for Cloudflare Workers
    // NOTE: This requires merjs to be built without libc for WASM targets.
    // Currently merjs has link_libc=true which prevents WASM compilation.
    // As a workaround, we build the native binary which can be deployed 
    // to any server. For true edge/WASM deployment, merjs needs modification.
    const worker_step = b.step("worker", "Build server binary (WASM not supported due to merjs libc dependency)");
    worker_step.dependOn(b.getInstallStep());
}
