const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const merjs_dep = b.dependency("merjs", .{});
    const mer_mod = merjs_dep.module("mer");
    const runtime_mod = merjs_dep.module("runtime");

    // Routes module (generated by nuri)
    const routes_mod = b.createModule(.{
        .root_source_file = b.path("src/generated/routes.zig"),
    });
    routes_mod.addImport("mer", mer_mod);

    // Layout module (optional, generated by nuri)
    const layout_mod: ?*std.Build.Module = blk: {
        _ = std.Io.Dir.cwd().statFile(b.graph.io, "src/app/layout.zig", .{}) catch break :blk null;
        const m = b.createModule(.{ .root_source_file = b.path("src/app/layout.zig") });
        m.addImport("mer", mer_mod);
        routes_mod.addImport("app/layout", m);
        break :blk m;
    };

    // Wire up each page module in src/app/
    var app_dir = std.Io.Dir.cwd().openDir(b.graph.io, "src/app", .{ .iterate = true }) catch {
        std.debug.print("nuri: no src/app/ directory found — run 'nuri build' first.\n", .{});
        return;
    };
    defer app_dir.close(b.graph.io);

    var walker = app_dir.walk(b.allocator) catch return;
    defer walker.deinit();
    while (walker.next(b.graph.io) catch null) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.path, ".zig")) continue;
        if (std.mem.eql(u8, entry.path, "layout.zig")) continue;

        const file_path = b.fmt("src/app/{s}", .{entry.path});
        const import_name = b.fmt("app/{s}", .{entry.path[0 .. entry.path.len - 4]});

        const page_mod = b.createModule(.{ .root_source_file = b.path(file_path) });
        page_mod.addImport("mer", mer_mod);
        if (layout_mod) |lm| page_mod.addImport("app/layout", lm);
        routes_mod.addImport(import_name, page_mod);
    }

    // Native executable for local development
    const main_mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    main_mod.addImport("mer", mer_mod);
    main_mod.addImport("runtime", runtime_mod);
    main_mod.addImport("routes", routes_mod);
    
    const exe = b.addExecutable(.{ .name = "nuri-site", .root_module = main_mod });
    b.installArtifact(exe);

    // zig build serve - Start dev server
    const run_exe = b.addRunArtifact(exe);
    run_exe.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_exe.addArgs(args);
    b.step("serve", "Start the dev server").dependOn(&run_exe.step);

    // zig build worker - Compile to WASM for Cloudflare Workers
    const wasm_target = b.resolveTargetQuery(.{
        .cpu_arch = .wasm32,
        .os_tag = .freestanding,
    });
    
    const worker_mod = b.createModule(.{
        .root_source_file = merjs_dep.path("src/worker.zig"),
        .target = wasm_target,
        .optimize = .ReleaseSmall,
    });
    worker_mod.addImport("mer", mer_mod);
    worker_mod.addImport("routes", routes_mod);
    
    // Add page modules to worker
    if (layout_mod) |lm| worker_mod.addImport("app/layout", lm);
    var app_dir2 = std.Io.Dir.cwd().openDir(b.graph.io, "src/app", .{ .iterate = true }) catch return;
    defer app_dir2.close(b.graph.io);
    var walker2 = app_dir2.walk(b.allocator) catch return;
    defer walker2.deinit();
    while (walker2.next(b.graph.io) catch null) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.path, ".zig")) continue;
        if (std.mem.eql(u8, entry.path, "layout.zig")) continue;
        const file_path = b.fmt("src/app/{s}", .{entry.path});
        const import_name = b.fmt("app/{s}", .{entry.path[0 .. entry.path.len - 4]});
        const page_mod = b.createModule(.{ .root_source_file = b.path(file_path) });
        page_mod.addImport("mer", mer_mod);
        if (layout_mod) |lm| page_mod.addImport("app/layout", lm);
        worker_mod.addImport(import_name, page_mod);
    }
    
    const worker_exe = b.addExecutable(.{ .name = "nuri-site", .root_module = worker_mod });
    worker_exe.rdynamic = true;
    worker_exe.entry = .disabled;
    
    const install_worker = b.addInstallFile(worker_exe.getEmittedBin(), "../worker/nuri-site.wasm");
    const worker_step = b.step("worker", "Compile to WASM for Cloudflare Workers");
    worker_step.dependOn(&install_worker.step);
}
