const std = @import("std");
const parser = @import("parser.zig");
const generator = @import("generator.zig");
const route_tree = @import("route_tree.zig");

const Command = enum {
    init,
    build,
    dev,
    help,
    unknown,
};

pub fn main(init: std.process.Init) !void {
    const args = init.minimal.args;
    
    var iter = args.iterate();
    
    // Skip program name
    _ = iter.next();
    
    const first_arg = iter.next() orelse {
        try printHelp();
        return;
    };

    const cmd = parseCommand(first_arg);

    switch (cmd) {
        .init => {
            const project_name = iter.next() orelse {
                std.debug.print("Error: init requires a project name\n", .{});
                std.debug.print("Usage: nuri init <name>\n", .{});
                return error.MissingProjectName;
            };
            try cmdInit(init, project_name);
        },
        .build => {
            try cmdBuild(init);
        },
        .dev => {
            try cmdDev(init);
        },
        .help => {
            try printHelp();
        },
        .unknown => {
            std.debug.print("Unknown command: {s}\n", .{first_arg});
            try printHelp();
            return error.UnknownCommand;
        },
    }
}

fn parseCommand(arg: []const u8) Command {
    if (std.mem.eql(u8, arg, "init")) return .init;
    if (std.mem.eql(u8, arg, "build")) return .build;
    if (std.mem.eql(u8, arg, "dev")) return .dev;
    if (std.mem.eql(u8, arg, "help") or std.mem.eql(u8, arg, "--help") or std.mem.eql(u8, arg, "-h")) return .help;
    return .unknown;
}

fn printHelp() !void {
    const help_text =
        \\Nuri - Static site generator for merjs
        \\
        \\Usage: nuri <command> [options]
        \\
        \\Commands:
        \\  init <name>    Create a new project
        \\  build          Build markdown files to merjs
        \\  dev            Watch, rebuild, and auto-restart merjs
        \\  help           Show this help message
        \\
        \\Quick Start:
        \\  nuri init my-site
        \\  cd my-site
        \\  nuri dev      # Watch files, rebuild, and serve on :3000
        \\
        \\The dev command will:
        \\  - Watch content/ for changes
        \\  - Rebuild markdown to src/app/
        \\  - Auto-restart merjs to pick up changes
        \\  - Press Ctrl+C to stop
        \\
    ;
    std.debug.print("{s}", .{help_text});
}

fn cmdInit(init: std.process.Init, name: []const u8) !void {
    const io = init.io;
    const allocator = init.gpa;
    
    std.debug.print("Creating project: {s}\n", .{name});

    const cwd = std.Io.Dir.cwd();
    
    cwd.createDir(io, name, .default_dir) catch |err| {
        if (err == error.PathAlreadyExists) {
            std.debug.print("Error: Directory '{s}' already exists\n", .{name});
            return error.DirectoryExists;
        }
        return err;
    };

    const project_path = try cwd.realPathFileAlloc(io, name, allocator);
    defer allocator.free(project_path);

    // 1. Create our project structure first
    const content_dir = try std.fs.path.join(allocator, &.{ project_path, "content" });
    defer allocator.free(content_dir);
    try cwd.createDir(io, content_dir, .default_dir);

    const app_dir_path = try std.fs.path.join(allocator, &.{ project_path, "src", "app" });
    defer allocator.free(app_dir_path);
    try cwd.createDirPath(io, app_dir_path);

    const public_dir = try std.fs.path.join(allocator, &.{ project_path, "public" });
    defer allocator.free(public_dir);
    try cwd.createDir(io, public_dir, .default_dir);

    // public/styles.css (default stylesheet)
    const styles_path = try std.fs.path.join(allocator, &.{ public_dir, "styles.css" });
    defer allocator.free(styles_path);
    try cwd.writeFile(io, .{ .sub_path = styles_path, .data = default_css, .flags = .{} });

    const generated_dir = try std.fs.path.join(allocator, &.{ project_path, "src", "generated" });
    defer allocator.free(generated_dir);
    try cwd.createDirPath(io, generated_dir);

    // content/index.md
    const sample_md =
        \\---
        \\title: Home
        \\---
        \\
        \\# Welcome to Nuri
        \\
        \\This is your first page with **bold** and *italic* text.
    ;
    const index_path = try std.fs.path.join(allocator, &.{ content_dir, "index.md" });
    defer allocator.free(index_path);
    try cwd.writeFile(io, .{ .sub_path = index_path, .data = sample_md, .flags = .{} });

    // nuri.config.json
    const config =
        \\{
        \\  "title": "My Nuri Site",
        \\  "description": "A site built with Nuri"
        \\}
    ;
    const config_path = try std.fs.path.join(allocator, &.{ project_path, "nuri.config.json" });
    defer allocator.free(config_path);
    try cwd.writeFile(io, .{ .sub_path = config_path, .data = config, .flags = .{} });

    // src/generated/routes.zig (empty stub)
    const routes_zig =
        \\// GENERATED by nuri — do not edit by hand.
        \\
        \\const Route = @import("mer").Route;
        \\
        \\pub const routes: []const Route = &.{};
    ;
    const routes_zig_path = try std.fs.path.join(allocator, &.{ generated_dir, "routes.zig" });
    defer allocator.free(routes_zig_path);
    try cwd.writeFile(io, .{ .sub_path = routes_zig_path, .data = routes_zig, .flags = .{} });

    // 2. Write build.zig
    const build_zig =
        \\const std = @import("std");
        \\
        \\pub fn build(b: *std.Build) void {
        \\    const target = b.standardTargetOptions(.{});
        \\    const optimize = b.standardOptimizeOption(.{});
        \\
        \\    const merjs_dep = b.dependency("merjs", .{});
        \\    const mer_mod = merjs_dep.module("mer");
        \\    const runtime_mod = merjs_dep.module("runtime");
        \\    // Note: prerender is accessed via mer_mod, not as separate module
        \\
        \\    // Routes module (generated by nuri)
        \\    const routes_mod = b.createModule(.{
        \\        .root_source_file = b.path("src/generated/routes.zig"),
        \\    });
        \\    routes_mod.addImport("mer", mer_mod);
        \\
        \\    // Layout module (optional, generated by nuri)
        \\    const layout_mod: ?*std.Build.Module = blk: {
        \\        _ = std.Io.Dir.cwd().statFile(b.graph.io, "src/app/layout.zig", .{}) catch break :blk null;
        \\        const m = b.createModule(.{ .root_source_file = b.path("src/app/layout.zig") });
        \\        m.addImport("mer", mer_mod);
        \\        m.addImport("routes", routes_mod);
        \\        routes_mod.addImport("app/layout", m);
        \\        break :blk m;
        \\    };
        \\
        \\    // Wire up each page module in src/app/
        \\    var app_dir = std.Io.Dir.cwd().openDir(b.graph.io, "src/app", .{ .iterate = true }) catch {
        \\        std.debug.print("nuri: no src/app/ directory found — run 'nuri build' first.\n", .{});
        \\        return;
        \\    };
        \\    defer app_dir.close(b.graph.io);
        \\
        \\    var walker = app_dir.walk(b.allocator) catch return;
        \\    defer walker.deinit();
        \\    while (walker.next(b.graph.io) catch null) |entry| {
        \\        if (entry.kind != .file) continue;
        \\        if (!std.mem.endsWith(u8, entry.path, ".zig")) continue;
        \\        if (std.mem.eql(u8, entry.path, "layout.zig")) continue;
        \\
        \\        const file_path = b.fmt("src/app/{s}", .{entry.path});
        \\        const import_name = b.fmt("app/{s}", .{entry.path[0 .. entry.path.len - 4]});
        \\
        \\        const page_mod = b.createModule(.{ .root_source_file = b.path(file_path) });
        \\        page_mod.addImport("mer", mer_mod);
        \\        if (layout_mod) |lm| page_mod.addImport("app/layout", lm);
        \\        routes_mod.addImport(import_name, page_mod);
        \\    }
        \\
        \\    // Main executable
        \\    const main_mod = b.createModule(.{
        \\        .root_source_file = b.path("src/main.zig"),
        \\        .target = target,
        \\        .optimize = optimize,
        \\        .link_libc = true,
        \\    });
        \\    main_mod.addImport("mer", mer_mod);
        \\    main_mod.addImport("runtime", runtime_mod);
        \\    main_mod.addImport("routes", routes_mod);
        \\
        \\    const exe = b.addExecutable(.{ .name = "nuri-site", .root_module = main_mod });
        \\    b.installArtifact(exe);
        \\
        \\    // zig build serve - Start dev server
        \\    const run_exe = b.addRunArtifact(exe);
        \\    run_exe.step.dependOn(b.getInstallStep());
        \\    if (b.args) |args| run_exe.addArgs(args);
        \\    b.step("serve", "Start the dev server").dependOn(&run_exe.step);
        \\
        \\    // zig build prerender - Static site generation
        \\    const run_prerender = b.addRunArtifact(exe);
        \\    run_prerender.addArg("--prerender");
        \\    run_prerender.step.dependOn(b.getInstallStep());
        \\    b.step("prerender", "Pre-render pages to dist/").dependOn(&run_prerender.step);
        \\
        \\    // zig build prod - Full production build
        \\    const prod_step = b.step("prod", "Full production build: compile + prerender to dist/");
        \\    prod_step.dependOn(b.getInstallStep());
        \\    prod_step.dependOn(&run_prerender.step);
        \\}
    ;

    const build_zig_path = try std.fs.path.join(allocator, &.{ project_path, "build.zig" });
    defer allocator.free(build_zig_path);
    try cwd.writeFile(io, .{ .sub_path = build_zig_path, .data = build_zig, .flags = .{} });

    // 5. Overwrite src/main.zig with our server entry point
    const src_main_zig =
        \\const std = @import("std");
        \\const mer = @import("mer");
        \\const runtime = @import("runtime");
        \\
        \\const log = std.log.scoped(.main);
        \\
        \\pub fn main(init: std.process.Init.Minimal) !void {
        \\    var gpa: std.heap.DebugAllocator(.{}) = .init;
        \\    defer _ = gpa.deinit();
        \\    const alloc = gpa.allocator();
        \\
        \\    try runtime.init(alloc);
        \\    defer runtime.deinit();
        \\
        \\    // Check for prerender mode
        \\    const args = try init.args.toSlice(alloc);
        \\    for (args) |arg| {
        \\        if (std.mem.eql(u8, arg, "--prerender")) {
        \\            std.debug.print("Prerendering static site to dist/...\n", .{});
        \\            var router = mer.Router.fromGenerated(alloc, @import("routes"));
        \\            defer router.deinit();
        \\            try mer.runPrerender(alloc, &router);
        \\            return;
        \\        }
        \\    }
        \\
        \\    var config = mer.Config{
        \\        .host = "127.0.0.1",
        \\        .port = 3000,
        \\        .dev = true,
        \\    };
        \\
        \\    var arena_state: std.heap.ArenaAllocator = .init(std.heap.page_allocator);
        \\    defer arena_state.deinit();
        \\    const arena_args = try init.args.toSlice(arena_state.allocator());
        \\
        \\    var i: usize = 1;
        \\    while (i < arena_args.len) : (i += 1) {
        \\        if (std.mem.eql(u8, arena_args[i], "--port") and i + 1 < arena_args.len) {
        \\            config.port = try std.fmt.parseInt(u16, arena_args[i + 1], 10);
        \\            i += 1;
        \\        } else if (std.mem.eql(u8, arena_args[i], "--no-dev")) {
        \\            config.dev = false;
        \\        } else if (std.mem.eql(u8, arena_args[i], "--verbose") or std.mem.eql(u8, arena_args[i], "-v")) {
        \\            config.verbose = true;
        \\        }
        \\    }
        \\
        \\    var router = mer.Router.fromGenerated(alloc, @import("routes"));
        \\    defer router.deinit();
        \\
        \\    var watcher = mer.Watcher.init(alloc, "src/app");
        \\    defer watcher.deinit();
        \\
        \\    if (config.dev) {
        \\        const wt = try std.Thread.spawn(.{}, mer.Watcher.run, .{&watcher});
        \\        wt.detach();
        \\        log.info("hot reload active — watching src/app/", .{});
        \\    }
        \\
        \\    var server = mer.Server.init(alloc, config, &router, if (config.dev) &watcher else null);
        \\    try server.listen();
        \\}
    ;

    const src_main_path = try std.fs.path.join(allocator, &.{ project_path, "src", "main.zig" });
    defer allocator.free(src_main_path);
    try cwd.writeFile(io, .{ .sub_path = src_main_path, .data = src_main_zig, .flags = .{} });

    // 4. Write build.zig.zon with placeholder fingerprint, then run `zig build` to get the real one
    const zon_path = try std.fs.path.join(allocator, &.{ project_path, "build.zig.zon" });
    defer allocator.free(zon_path);

    const zon_template =
        \\.{
        \\    .name = .nuri_site,
        \\    .fingerprint = 0x0,
        \\    .version = "0.1.0",
        \\    .minimum_zig_version = "0.16.0",
        \\    .dependencies = .{
        \\        .merjs = .{
        \\            .url = "git+https://github.com/ivanleomk/merjs.git#93519ad5fdfbd2350a1ca051a391c3dee60b0b02",
        \\            .hash = "merjs-0.2.5-qL9LkovAYADBMdEWeU1UdlopMdgX_cYo8BTsMjRBVm0Q",
        \\        },
        \\    },
        \\    .paths = .{
        \\        "build.zig",
        \\        "build.zig.zon",
        \\        "src",
        \\    },
        \\}
    ;
    try cwd.writeFile(io, .{ .sub_path = zon_path, .data = zon_template, .flags = .{} });

    // Run `zig build` to get the correct fingerprint from the error message
    var zig_build = try std.process.spawn(io, .{
        .argv = &[_][]const u8{ "zig", "build" },
        .cwd = .{ .path = project_path },
        .stdin = .ignore,
        .stdout = .ignore,
        .stderr = .pipe,
    });
    var stderr_buf: [4096]u8 = undefined;
    const stderr_len = zig_build.stderr.?.readStreaming(io, &.{&stderr_buf}) catch 0;
    _ = try zig_build.wait(io);
    const stderr_output = stderr_buf[0..stderr_len];

    // Parse "use this value: 0x..." from stderr and patch build.zig.zon
    if (std.mem.indexOf(u8, stderr_output, "use this value: 0x")) |idx| {
        const hex_start = idx + "use this value: ".len;
        var hex_end = hex_start + 2; // skip "0x"
        while (hex_end < stderr_output.len and isHexChar(stderr_output[hex_end])) {
            hex_end += 1;
        }
        const correct_fingerprint = stderr_output[hex_start..hex_end];

        // Rewrite build.zig.zon with correct fingerprint
        var zon_buf = std.ArrayList(u8).empty;
        defer zon_buf.deinit(allocator);
        var line_iter = std.mem.splitScalar(u8, zon_template, '\n');
        var first = true;
        while (line_iter.next()) |line| {
            if (!first) try zon_buf.append(allocator, '\n');
            first = false;
            if (std.mem.indexOf(u8, line, ".fingerprint = 0x0,") != null) {
                try zon_buf.appendSlice(allocator, "    .fingerprint = ");
                try zon_buf.appendSlice(allocator, correct_fingerprint);
                try zon_buf.append(allocator, ',');
            } else {
                try zon_buf.appendSlice(allocator, line);
            }
        }
        try cwd.writeFile(io, .{ .sub_path = zon_path, .data = zon_buf.items, .flags = .{} });
    }

    std.debug.print("✓ Created project in ./{s}/\n", .{name});
    std.debug.print("\nNext steps:\n", .{});
    std.debug.print("  cd {s}\n", .{name});
    std.debug.print("  nuri dev\n", .{});
}

fn cmdBuild(init: std.process.Init) !void {
    const io = init.io;
    const allocator = init.gpa;
    
    const cwd = std.Io.Dir.cwd();
    
    var content_dir = cwd.openDir(io, "content", .{ .iterate = true }) catch |err| {
        if (err == error.FileNotFound) {
            std.debug.print("Error: No content/ directory found. Run 'nuri init <name>' first.\n", .{});
            return error.NoContentDirectory;
        }
        return err;
    };
    defer content_dir.close(io);

    // Clean src/app/ so deleted markdown files don't leave stale .zig routes
    try cleanGeneratedFiles(io, allocator);

    cwd.createDirPath(io, "src/app") catch |err| {
        if (err != error.PathAlreadyExists) {
            return err;
        }
    };

    std.debug.print("Building markdown files...\n", .{});

    var walker = try content_dir.walk(allocator);
    defer walker.deinit();

    var file_count: usize = 0;

    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.basename, ".md")) continue;

        const content_path = try std.fs.path.join(allocator, &.{ "content", entry.path });
        defer allocator.free(content_path);

        const output_path = blk: {
            const base_name = entry.basename[0 .. entry.basename.len - 3];
            const rel_dir = std.fs.path.dirname(entry.path) orelse "";
            if (rel_dir.len == 0) {
                break :blk try std.fmt.allocPrint(allocator, "src/app/{s}.zig", .{base_name});
            } else {
                break :blk try std.fmt.allocPrint(allocator, "src/app/{s}/{s}.zig", .{ rel_dir, base_name });
            }
        };
        defer allocator.free(output_path);

        try processMarkdownFile(init, content_path, output_path);
        file_count += 1;
        std.debug.print("  ✓ {s} → {s}\n", .{ entry.path, output_path });
    }

    if (file_count == 0) {
        std.debug.print("Warning: No .md files found in content/\n", .{});
    } else {
        std.debug.print("\nBuilt {d} file(s)\n", .{file_count});
    }

    // Ensure content/index.md exists — every site needs a homepage
    _ = cwd.statFile(io, "content/index.md", .{}) catch {
        std.debug.print("Error: content/index.md is required (every site needs a homepage)\n", .{});
        return error.MissingIndexPage;
    };

    // Generate default layout with CSS styling
    try generateLayout(io, cwd);

    // Generate src/generated/routes.zig
    try generateRoutes(init);
}

fn processMarkdownFile(init: std.process.Init, input_path: []const u8, output_path: []const u8) !void {
    const io = init.io;
    const allocator = init.gpa;
    
    const cwd = std.Io.Dir.cwd();
    
    // Read markdown file
    const content = try cwd.readFileAlloc(io, input_path, allocator, .unlimited);
    defer allocator.free(content);

    // Parse markdown
    var doc = try parser.parse(allocator, content);
    defer doc.deinit(allocator);

    // Generate merjs code
    const output = try generator.generate(allocator, doc, content);
    defer allocator.free(output);

    // Ensure output directory exists
    const output_dir = std.fs.path.dirname(output_path) orelse return error.InvalidPath;
    try cwd.createDirPath(io, output_dir);

    // Write output file
    try cwd.writeFile(io, .{
        .sub_path = output_path,
        .data = output,
        .flags = .{},
    });
}

fn generateLayout(io: std.Io, cwd: std.Io.Dir) !void {
    const layout_zig =
        \\const std = @import("std");
        \\const mer = @import("mer");
        \\const routes = @import("routes");
        \\
        \\pub fn wrap(allocator: std.mem.Allocator, path: []const u8, body: []const u8, meta: mer.Meta) []const u8 {
        \\    const title = if (meta.title.len > 0) meta.title else if (std.mem.eql(u8, path, "/")) "Home" else if (path.len > 1) path[1..] else "Nuri";
        \\    const desc = if (meta.description.len > 0) meta.description else "Built with Nuri";
        \\
        \\    var buf: std.ArrayList(u8) = .empty;
        \\
        \\    buf.appendSlice(allocator,
        \\        \\<!DOCTYPE html>
        \\        \\<html lang="en">
        \\        \\<head>
        \\        \\  <meta charset="UTF-8">
        \\        \\  <meta name="viewport" content="width=device-width, initial-scale=1.0">
        \\        \\  <link rel="stylesheet" href="/styles.css">
        \\        \\
        \\    ) catch return body;
        \\
        \\    buf.print(allocator, "  <title>{s}</title>\n", .{title}) catch return body;
        \\    buf.print(allocator, "  <meta name=\"description\" content=\"{s}\">\n", .{desc}) catch return body;
        \\
        \\    if (meta.extra_head) |extra| {
        \\        buf.appendSlice(allocator, extra) catch {};
        \\        buf.appendSlice(allocator, "\n") catch {};
        \\    }
        \\
        \\    buf.appendSlice(allocator,
        \\        \\</head>
        \\        \\<body>
        \\        \\<div class="layout">
        \\        \\  <aside class="route-sidebar-container">
        \\        \\    
        \\    ) catch return body;
        \\
        \\    buf.appendSlice(allocator, routes.sidebarHtml(path)) catch return body;
        \\    
        \\    buf.appendSlice(allocator,
        \\        \\  </aside>
        \\        \\  <main class="main-content">
        \\        \\    
        \\    ) catch return body;
        \\
        \\    buf.appendSlice(allocator, body) catch return body;
        \\
        \\    buf.appendSlice(allocator,
        \\        \\  </main>
        \\        \\</div>
        \\        \\</body>
        \\        \\</html>
        \\    ) catch return body;
        \\
        \\    return buf.items;
        \\}
    ;

    try cwd.writeFile(io, .{
        .sub_path = "src/app/layout.zig",
        .data = layout_zig,
        .flags = .{},
    });
    std.debug.print("  ✓ Generated src/app/layout.zig\n", .{});

    // Write default public/styles.css (only if it doesn't exist yet — user can customize)
    _ = cwd.statFile(io, "public/styles.css", .{}) catch {
        try cwd.writeFile(io, .{
            .sub_path = "public/styles.css",
            .data = default_css,
            .flags = .{},
        });
        std.debug.print("  ✓ Created public/styles.css (default styles)\n", .{});
        return;
    };
}

const default_css =
    \\/* Nuri docs — clean Mintlify-inspired light theme. Edit freely, this file won't be overwritten. */
    \\@import url('https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@600;700;800&family=Source+Sans+3:ital,wght@0,400;0,500;0,600;1,400&family=JetBrains+Mono:wght@400;500&display=swap');
    \\
    \\*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    \\
    \\:root {
    \\  --accent: oklch(0.55 0.14 160);
    \\  --accent-hover: oklch(0.48 0.14 160);
    \\  --accent-subtle: oklch(0.95 0.02 160);
    \\  --accent-text: oklch(0.42 0.1 160);
    \\  --bg: oklch(0.985 0.003 160);
    \\  --bg-page: oklch(1 0 0);
    \\  --surface: oklch(0.975 0.004 160);
    \\  --border: oklch(0.92 0.005 160);
    \\  --border-strong: oklch(0.88 0.008 160);
    \\  --text: oklch(0.22 0.01 160);
    \\  --text-secondary: oklch(0.44 0.01 160);
    \\  --text-muted: oklch(0.58 0.01 160);
    \\  --code-bg: oklch(0.96 0.005 160);
    \\  --code-text: oklch(0.42 0.08 160);
    \\  --pre-bg: oklch(0.16 0.01 260);
    \\  --pre-text: oklch(0.88 0.01 260);
    \\  --space-xs: 4px;
    \\  --space-sm: 8px;
    \\  --space-md: 16px;
    \\  --space-lg: 24px;
    \\  --space-xl: 32px;
    \\  --space-2xl: 48px;
    \\  --space-3xl: 64px;
    \\  --radius: 8px;
    \\  --radius-sm: 6px;
    \\  --content-max: 680px;
    \\  --sidebar-width: 220px;
    \\}
    \\
    \\html { scroll-behavior: smooth; }
    \\
    \\body {
    \\  background: var(--bg);
    \\  color: var(--text);
    \\  font-family: 'Source Sans 3', system-ui, -apple-system, sans-serif;
    \\  font-size: 16px;
    \\  line-height: 1.7;
    \\  min-height: 100vh;
    \\  -webkit-font-smoothing: antialiased;
    \\  -moz-osx-font-smoothing: grayscale;
    \\}
    \\
    \\::selection {
    \\  background: oklch(0.85 0.08 160);
    \\  color: var(--text);
    \\}
    \\
    \\.layout {
    \\  display: flex;
    \\  min-height: 100vh;
    \\}
    \\
    \\.route-sidebar-container {
    \\  width: 260px;
    \\  flex-shrink: 0;
    \\  background: var(--surface);
    \\  border-right: 1px solid var(--border);
    \\  padding: var(--space-xl) var(--space-lg);
    \\  position: fixed;
    \\  height: 100vh;
    \\  overflow-y: auto;
    \\}
    \\
    \\.main-content {
    \\  flex: 1;
    \\  margin-left: 260px;
    \\  padding: var(--space-xl);
    \\  max-width: calc(100% - 260px);
    \\}
    \\
    \\/* Route Sidebar Styles */
    \\.route-sidebar { }
    \\
    \\a.route-sidebar-header {
    \\  font-family: 'Bricolage Grotesque', system-ui, sans-serif;
    \\  font-weight: 700;
    \\  font-size: 0.875rem;
    \\  color: var(--text);
    \\  text-transform: uppercase;
    \\  letter-spacing: 0.05em;
    \\  margin-bottom: var(--space-md);
    \\  padding-bottom: var(--space-sm);
    \\  border-bottom: 1px solid var(--border);
    \\  display: flex;
    \\  align-items: center;
    \\  gap: 12px;
    \\  text-decoration: none;
    \\  transition: color 0.15s ease;
    \\}
    \\
    \\a.route-sidebar-header:hover {
    \\  color: var(--accent);
    \\}
    \\
    \\.route-sidebar-header .home-icon {
    \\  flex-shrink: 0;
    \\  vertical-align: middle;
    \\}
    \\
    \\.route-tree,
    \\.route-children {
    \\  list-style: none;
    \\  padding: 0;
    \\  margin: 0;
    \\}
    \\
    \\.route-tree li {
    \\  margin: 0;
    \\}
    \\
    \\.route-tree a,
    \\.route-tree .section-header {
    \\  display: block;
    \\  padding: 6px 8px;
    \\  color: var(--text-secondary);
    \\  font-size: 0.9rem;
    \\  text-decoration: none;
    \\  border-radius: var(--radius-sm);
    \\  transition: all 0.15s ease;
    \\  margin-bottom: 2px;
    \\}
    \\
    \\.route-tree a:hover {
    \\  color: var(--accent-text);
    \\  background: var(--accent-subtle);
    \\}
    \\
    \\.route-tree a.active {
    \\  color: var(--accent);
    \\  font-weight: 600;
    \\  background: var(--accent-subtle);
    \\}
    \\
    \\.route-tree .section-header {
    \\  font-weight: 600;
    \\  color: var(--text);
    \\  margin-top: var(--space-sm);
    \\}
    \\
    \\.route-children {
    \\  padding-left: var(--space-md);
    \\  border-left: 1px solid var(--border);
    \\  margin-left: 8px;
    \\}
    \\
    \\.route-children a {
    \\  font-size: 0.85rem;
    \\}
    \\
    \\/* Mobile responsive */
    \\@media (max-width: 768px) {
    \\  .route-sidebar-container {
    \\    display: none;
    \\  }
    \\  .main-content {
    \\    margin-left: 0;
    \\    max-width: 100%;
    \\  }
    \\}
    \\
    \\.page-wrapper {
    \\  display: flex;
    \\  flex-direction: column;
    \\  max-width: 960px;
    \\  margin: 0 auto;
    \\  padding: var(--space-lg) var(--space-md);
    \\  gap: var(--space-lg);
    \\}
    \\
    \\.toc {
    \\  padding: 0 0 0 var(--space-lg);
    \\  border-left: 1px solid var(--border);
    \\}
    \\
    \\.toc-header {
    \\  font-family: 'Source Sans 3', system-ui, sans-serif;
    \\  font-weight: 600;
    \\  font-size: 0.8em;
    \\  color: var(--text-muted);
    \\  text-transform: uppercase;
    \\  letter-spacing: 0.08em;
    \\  margin-bottom: 12px;
    \\  padding-bottom: var(--space-sm);
    \\  border-bottom: 1px solid var(--border);
    \\}
    \\
    \\.toc ul { list-style: none; }
    \\.toc li { margin: 0; }
    \\
    \\.toc a {
    \\  display: block;
    \\  padding: 4px 0;
    \\  color: var(--text-secondary);
    \\  font-size: 0.8rem;
    \\  font-weight: 400;
    \\  text-decoration: none;
    \\  border-left: 2px solid transparent;
    \\  padding-left: var(--space-md);
    \\  margin-left: calc(-1 * var(--space-md) - 2px);
    \\  transition: color 0.15s ease, border-color 0.15s ease;
    \\}
    \\
    \\.toc a:hover {
    \\  color: var(--text);
    \\}
    \\
    \\.toc a.active {
    \\  color: var(--accent-text);
    \\  border-left-color: var(--accent);
    \\}
    \\
    \\.toc-h1 a {
    \\  font-weight: 500;
    \\  color: var(--text);
    \\}
    \\
    \\.toc-h2 a { margin-left: calc(-1 * var(--space-md) - 2px + 12px); }
    \\.toc-h3 a { 
    \\  margin-left: calc(-1 * var(--space-md) - 2px + 24px); 
    \\  font-size: 0.75rem; 
    \\}
    \\
    \\.page-content {
    \\  flex: 1;
    \\  max-width: var(--content-max);
    \\  padding: 0;
    \\}
    \\
    \\@media (min-width: 900px) {
    \\  .page-wrapper {
    \\    flex-direction: row;
    \\    max-width: 1060px;
    \\    padding: var(--space-2xl) var(--space-xl);
    \\    gap: var(--space-2xl);
    \\    justify-content: center;
    \\  }
    \\  .page-content {
    \\    flex: 1;
    \\    padding-bottom: 120px;
    \\    min-width: 0;
    \\    order: 1;
    \\  }
    \\  .toc {
    \\    position: sticky;
    \\    top: var(--space-xl);
    \\    width: var(--sidebar-width);
    \\    height: fit-content;
    \\    max-height: calc(100vh - var(--space-3xl));
    \\    overflow-y: auto;
    \\    flex-shrink: 0;
    \\    border-left: 1px solid var(--border);
    \\    background: transparent;
    \\    padding: 0 0 0 var(--space-lg);
    \\    border-radius: 0;
    \\    order: 2;
    \\  }
    \\  .toc-header {
    \\    font-size: 0.75rem;
    \\    font-weight: 600;
    \\    color: var(--text-muted);
    \\    text-transform: uppercase;
    \\    letter-spacing: 0.05em;
    \\    margin-bottom: var(--space-sm);
    \\    border-bottom: none;
    \\    padding-bottom: 0;
    \\  }
    \\}
    \\
    \\@media (min-width: 600px) and (max-width: 899px) {
    \\  .page-wrapper { padding: var(--space-xl) var(--space-lg); }
    \\}
    \\
    \\.title {
    \\  font-family: 'Bricolage Grotesque', system-ui, sans-serif;
    \\  font-size: clamp(2em, 4vw, 2.5em);
    \\  font-weight: 800;
    \\  letter-spacing: -0.03em;
    \\  line-height: 1.15;
    \\  color: var(--text);
    \\  margin-bottom: var(--space-md);
    \\}
    \\
    \\.subtitle {
    \\  font-family: 'Bricolage Grotesque', system-ui, sans-serif;
    \\  font-size: 1.3em;
    \\  font-weight: 700;
    \\  letter-spacing: -0.02em;
    \\  color: var(--text);
    \\  margin-top: var(--space-2xl);
    \\  margin-bottom: 12px;
    \\}
    \\
    \\.heading {
    \\  font-family: 'Bricolage Grotesque', system-ui, sans-serif;
    \\  font-size: 1.1em;
    \\  font-weight: 600;
    \\  color: var(--text);
    \\  margin-top: var(--space-lg);
    \\  margin-bottom: var(--space-sm);
    \\}
    \\
    \\p {
    \\  margin-bottom: var(--space-md);
    \\  color: var(--text-secondary);
    \\  line-height: 1.75;
    \\}
    \\
    \\strong { font-weight: 600; color: var(--text); }
    \\
    \\a {
    \\  color: var(--accent);
    \\  text-decoration: underline;
    \\  text-decoration-color: oklch(0.7 0.08 160);
    \\  text-underline-offset: 2px;
    \\  transition: color 0.15s ease, text-decoration-color 0.15s ease;
    \\}
    \\
    \\a:hover {
    \\  color: var(--accent-hover);
    \\  text-decoration-color: var(--accent-hover);
    \\}
    \\
    \\ul, ol {
    \\  margin-bottom: var(--space-md);
    \\  padding-left: var(--space-lg);
    \\}
    \\
    \\li {
    \\  margin-bottom: var(--space-sm);
    \\  color: var(--text-secondary);
    \\  line-height: 1.7;
    \\}
    \\
    \\li::marker { color: var(--text-muted); }
    \\
    \\code {
    \\  font-family: 'JetBrains Mono', ui-monospace, 'Cascadia Code', monospace;
    \\  font-size: 0.85em;
    \\  background: var(--code-bg);
    \\  border: 1px solid var(--border);
    \\  border-radius: 4px;
    \\  padding: 1px 6px;
    \\  color: var(--code-text);
    \\}
    \\
    \\pre {
    \\  background: var(--pre-bg);
    \\  border-radius: var(--radius);
    \\  padding: var(--space-md) var(--space-lg);
    \\  overflow-x: auto;
    \\  margin-bottom: var(--space-md);
    \\  font-size: 0.85em;
    \\  line-height: 1.65;
    \\}
    \\
    \\pre code {
    \\  background: none;
    \\  border: none;
    \\  padding: 0;
    \\  color: var(--pre-text);
    \\  font-size: inherit;
    \\}
    \\
    \\blockquote {
    \\  background: var(--accent-subtle);
    \\  padding: 14px var(--space-lg);
    \\  margin-bottom: var(--space-md);
    \\  color: var(--text-secondary);
    \\  border-radius: var(--radius);
    \\  font-style: italic;
    \\}
    \\
    \\blockquote p { color: var(--text-secondary); margin-bottom: 0; }
    \\
    \\hr {
    \\  border: none;
    \\  height: 1px;
    \\  background: var(--border);
    \\  margin: var(--space-2xl) 0;
    \\}
    \\
    \\table {
    \\  width: 100%;
    \\  border-collapse: collapse;
    \\  margin-bottom: var(--space-md);
    \\  font-size: 0.9em;
    \\}
    \\
    \\th, td {
    \\  padding: 10px 14px;
    \\  text-align: left;
    \\  border-bottom: 1px solid var(--border);
    \\}
    \\
    \\th {
    \\  font-weight: 600;
    \\  color: var(--text-muted);
    \\  font-size: 0.8em;
    \\  text-transform: uppercase;
    \\  letter-spacing: 0.05em;
    \\}
    \\
    \\td { color: var(--text-secondary); }
    \\tr:last-child td { border-bottom: none; }
;

const RouteInfo = struct {
    path: []const u8,
    url: []const u8,
    title: ?[]const u8,
    description: ?[]const u8,
};

fn generateRoutes(init: std.process.Init) !void {
    const io = init.io;
    const allocator = init.gpa;
    const cwd = std.Io.Dir.cwd();

    // Scan src/app/ for .zig files and build tree structure
    var file_paths: std.ArrayList([]const u8) = .empty;
    defer {
        for (file_paths.items) |p| allocator.free(p);
        file_paths.deinit(allocator);
    }

    var app_dir = cwd.openDir(io, "src/app", .{ .iterate = true }) catch return;
    defer app_dir.close(io);

    var walker = try app_dir.walk(allocator);
    defer walker.deinit();

    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.path, ".zig")) continue;
        // Skip layout.zig — it's a shared layout module, not a route
        if (std.mem.eql(u8, entry.path, "layout.zig")) continue;
        const full = try std.fmt.allocPrint(allocator, "app/{s}", .{entry.path});
        try file_paths.append(allocator, full);
    }

    // Build route tree
    var tree = try route_tree.buildRouteTree(allocator, file_paths.items);
    defer tree.deinit();

    // Print tree structure for debugging
    std.debug.print("\n  Route Tree Structure:\n", .{});
    var tree_buf: std.ArrayList(u8) = .empty;
    defer tree_buf.deinit(allocator);
    try tree.generateTreeView(&tree_buf, allocator);
    std.debug.print("{s}", .{tree_buf.items});
    std.debug.print("\n", .{});

    // Collect all routes in sorted order
    var routes_list: std.ArrayList(*route_tree.RouteNode) = .empty;
    defer routes_list.deinit(allocator);
    try tree.getAllRoutes(&routes_list);
    
    // Collect route metadata from markdown files
    var route_infos: std.ArrayList(RouteInfo) = .empty;
    defer {
        for (route_infos.items) |info| {
            allocator.free(info.path);
            allocator.free(info.url);
            if (info.title) |t| allocator.free(t);
            if (info.description) |d| allocator.free(d);
        }
        route_infos.deinit(allocator);
    }
    
    // Parse markdown files to get metadata
    for (routes_list.items) |node| {
        if (node.file_path) |path| {
            const url = try route_tree.toUrl(allocator, path);
            
            // Convert app/path.zig to content/path.md
            const without_prefix = if (std.mem.startsWith(u8, path, "app/")) path[4..] else path;
            const without_ext = if (std.mem.endsWith(u8, without_prefix, ".zig")) without_prefix[0..without_prefix.len - 4] else without_prefix;
            const md_path = try std.fmt.allocPrint(allocator, "content/{s}.md", .{without_ext});
            defer allocator.free(md_path);
            
            // Try to read and parse the markdown file
            var title: ?[]const u8 = null;
            var description: ?[]const u8 = null;
            
            const md_content = cwd.readFileAlloc(io, md_path, allocator, .unlimited) catch null;
            if (md_content) |content| {
                defer allocator.free(content);
                
                const doc = parser.parse(allocator, content) catch null;
                if (doc) |d| {
                    defer d.deinit(allocator);
                    if (d.meta.title) |t| {
                        title = try allocator.dupe(u8, t);
                    }
                    if (d.meta.description) |d_| {
                        description = try allocator.dupe(u8, d_);
                    }
                }
            }
            
            try route_infos.append(allocator, .{
                .path = try allocator.dupe(u8, path),
                .url = url,
                .title = title,
                .description = description,
            });
        }
    }

    // Build routes.zig content
    var buf = std.ArrayList(u8).empty;
    defer buf.deinit(allocator);

    try buf.appendSlice(allocator,
        \\// GENERATED by nuri — do not edit by hand.
        \\
        \\const std = @import("std");
        \\const mer = @import("mer");
        \\const Route = mer.Route;
        \\
        \\
    );

    // Generate imports for all routes
    for (routes_list.items) |node| {
        if (node.file_path) |path| {
            const ident = try route_tree.toIdent(allocator, path);
            defer allocator.free(ident);
            const import_name = path[0 .. path.len - 4]; // strip .zig
            try buf.print(allocator, "const {s} = @import(\"{s}\");\n", .{ ident, import_name });
        }
    }

    try buf.appendSlice(allocator, "\npub const routes: []const Route = &.{\n");
    
    // Generate route entries in tree order (sorted)
    for (routes_list.items) |node| {
        if (node.file_path) |path| {
            const ident = try route_tree.toIdent(allocator, path);
            defer allocator.free(ident);
            const url = try route_tree.toUrl(allocator, path);
            defer allocator.free(url);
            try buf.print(allocator, "    .{{ .path = \"{s}\", .render = {s}.render, .render_stream = if (@hasDecl({s}, \"renderStream\")) {s}.renderStream else null, .meta = if (@hasDecl({s}, \"meta\")) {s}.meta else .{{}}, .prerender = if (@hasDecl({s}, \"prerender\")) {s}.prerender else false }},\n", .{ url, ident, ident, ident, ident, ident, ident, ident });
        }
    }
    // Add llms.txt route for Cloudflare Workers
    try buf.appendSlice(allocator, "    .{ .path = \"/.well-known/llms.txt\", .render = llmsTxtRender, .meta = .{ .title = \"LLMs.txt\", .description = \"Available routes\" }, .prerender = false },\n");
    try buf.appendSlice(allocator, "};\n\n");
    
    // Read nuri.config.json for site info
    var site_title: ?[]const u8 = null;
    var site_desc: ?[]const u8 = null;
    const config_content = cwd.readFileAlloc(io, "nuri.config.json", allocator, .unlimited) catch null;
    if (config_content) |content| {
        defer allocator.free(content);
        // Simple JSON parsing - look for "title" and "description" fields
        if (std.mem.indexOf(u8, content, "\"title\"")) |title_start| {
            if (std.mem.indexOfScalarPos(u8, content, title_start + 8, '"')) |quote_start| {
                const value_start = quote_start + 1;
                if (std.mem.indexOfScalarPos(u8, content, value_start, '"')) |quote_end| {
                    site_title = try allocator.dupe(u8, content[value_start..quote_end]);
                }
            }
        }
        if (std.mem.indexOf(u8, content, "\"description\"")) |desc_start| {
            if (std.mem.indexOfScalarPos(u8, content, desc_start + 14, '"')) |quote_start| {
                const value_start = quote_start + 1;
                if (std.mem.indexOfScalarPos(u8, content, value_start, '"')) |quote_end| {
                    site_desc = try allocator.dupe(u8, content[value_start..quote_end]);
                }
            }
        }
    }
    defer {
        if (site_title) |t| allocator.free(t);
        if (site_desc) |d| allocator.free(d);
    }

    // Generate llms.txt render function
    try buf.appendSlice(allocator, "fn llmsTxtRender(_req: mer.Request) mer.Response {\n");
    try buf.appendSlice(allocator, "    _ = _req;\n");
    
    // Build the llms.txt content
    var llms_buf: std.ArrayList(u8) = .empty;
    defer llms_buf.deinit(allocator);
    
    // Header with site title
    if (site_title) |title| {
        try llms_buf.appendSlice(allocator, "# ");
        try llms_buf.appendSlice(allocator, title);
        try llms_buf.appendSlice(allocator, "\n\n");
    } else {
        try llms_buf.appendSlice(allocator, "# Site\n\n");
    }
    
    // Site description as blockquote
    if (site_desc) |desc| {
        try llms_buf.appendSlice(allocator, "> ");
        try llms_buf.appendSlice(allocator, desc);
        try llms_buf.appendSlice(allocator, "\n\n");
    }
    
    // Pages section
    try llms_buf.appendSlice(allocator, "## Pages\n\n");
    
    for (route_infos.items) |info| {
        if (info.title) |title| {
            try llms_buf.appendSlice(allocator, "- [");
            try llms_buf.appendSlice(allocator, title);
            try llms_buf.appendSlice(allocator, "](");
            try llms_buf.appendSlice(allocator, info.url);
            try llms_buf.appendSlice(allocator, ")");
            if (info.description) |desc| {
                try llms_buf.appendSlice(allocator, ": ");
                try llms_buf.appendSlice(allocator, desc);
            }
            try llms_buf.appendSlice(allocator, "\n");
        } else {
            // Fallback to URL if no title
            try llms_buf.appendSlice(allocator, "- [");
            try llms_buf.appendSlice(allocator, info.url);
            try llms_buf.appendSlice(allocator, "](");
            try llms_buf.appendSlice(allocator, info.url);
            try llms_buf.appendSlice(allocator, ")\n");
        }
    }
    
    // Escape the content for Zig string
    try buf.appendSlice(allocator, "    const content = \"");
    for (llms_buf.items) |c| {
        switch (c) {
            '\\' => try buf.appendSlice(allocator, "\\\\"),
            '"' => try buf.appendSlice(allocator, "\\\""),
            '\n' => try buf.appendSlice(allocator, "\\n"),
            else => try buf.append(allocator, c),
        }
    }
    try buf.appendSlice(allocator, "\";\n");
    try buf.appendSlice(allocator, "    return mer.text(.ok, content);\n");
    try buf.appendSlice(allocator, "}\n\n");

    // Generate sidebar HTML for each route with proper active state
    try buf.appendSlice(allocator, "/// Sidebar HTML for route navigation\n");
    try buf.appendSlice(allocator, "pub fn sidebarHtml(current_path: []const u8) []const u8 {\n");
    try buf.appendSlice(allocator, "    // Use comptime-generated lookup based on current path\n");
    try buf.appendSlice(allocator, "    return sidebarForPath(current_path);\n");
    try buf.appendSlice(allocator, "}\n\n");
    
    // Generate a function that returns the correct sidebar for each path
    try buf.appendSlice(allocator, "fn sidebarForPath(path: []const u8) []const u8 {\n");
    
    // Generate switch cases for each route
    for (routes_list.items) |node| {
        if (node.file_path) |path| {
            const url = try route_tree.toUrl(allocator, path);
            defer allocator.free(url);
            
            // Generate sidebar HTML for this specific route
            const sidebar_html = try tree.generateSidebarHtml(allocator, url);
            defer allocator.free(sidebar_html);
            
            // Write case: "/path" => return "<sidebar html>",
            try buf.appendSlice(allocator, "    if (std.mem.eql(u8, path, \"");
            try buf.appendSlice(allocator, url);
            try buf.appendSlice(allocator, "\")) return \"");
            
            // Escape the sidebar HTML for embedding in Zig string
            for (sidebar_html) |c| {
                switch (c) {
                    '\\' => try buf.appendSlice(allocator, "\\\\"),
                    '"' => try buf.appendSlice(allocator, "\\\""),
                    '\n' => try buf.appendSlice(allocator, "\\n"),
                    else => try buf.append(allocator, c),
                }
            }
            try buf.appendSlice(allocator, "\";\n");
        }
    }
    
    // Default case - return sidebar for root
    const default_sidebar = try tree.generateSidebarHtml(allocator, "/");
    defer allocator.free(default_sidebar);
    try buf.appendSlice(allocator, "    // Default: root sidebar\n");
    try buf.appendSlice(allocator, "    return \"");
    for (default_sidebar) |c| {
        switch (c) {
            '\\' => try buf.appendSlice(allocator, "\\\\"),
            '"' => try buf.appendSlice(allocator, "\\\""),
            '\n' => try buf.appendSlice(allocator, "\\n"),
            else => try buf.append(allocator, c),
        }
    }
    try buf.appendSlice(allocator, "\";\n");
    try buf.appendSlice(allocator, "}\n\n");

    // Wire up layout if it exists
    const has_layout = blk: {
        _ = cwd.statFile(io, "src/app/layout.zig", .{}) catch break :blk false;
        break :blk true;
    };
    if (has_layout) {
        try buf.appendSlice(allocator, "const app_layout = @import(\"app/layout\");\n");
        try buf.appendSlice(allocator, "pub const layout = app_layout.wrap;\n");
        try buf.appendSlice(allocator, "pub const streamLayout = if (@hasDecl(app_layout, \"streamWrap\")) app_layout.streamWrap else null;\n");
    }

    // Ensure output directory exists
    cwd.createDirPath(io, "src/generated") catch |err| {
        if (err != error.PathAlreadyExists) return err;
    };

    try cwd.writeFile(io, .{
        .sub_path = "src/generated/routes.zig",
        .data = buf.items,
        .flags = .{},
    });

    std.debug.print("  ✓ Generated src/generated/routes.zig ({d} routes)\n\n", .{routes_list.items.len});
}

/// "app/about.zig" → "app_about"
fn toIdent(allocator: std.mem.Allocator, path: []const u8) ![]u8 {
    const without_ext = if (std.mem.endsWith(u8, path, ".zig")) path[0 .. path.len - 4] else path;
    const buf = try allocator.dupe(u8, without_ext);
    for (buf) |*c| {
        if (c.* != '_' and (c.* < 'a' or c.* > 'z') and (c.* < 'A' or c.* > 'Z') and (c.* < '0' or c.* > '9')) {
            c.* = '_';
        }
    }
    return buf;
}

/// URL mapping: app/index.zig → "/", app/about.zig → "/about"
fn toUrl(allocator: std.mem.Allocator, path: []const u8) ![]u8 {
    const without_ext = if (std.mem.endsWith(u8, path, ".zig")) path[0 .. path.len - 4] else path;

    // Strip "app/" prefix
    const rel = if (std.mem.startsWith(u8, without_ext, "app/"))
        without_ext["app/".len..]
    else
        without_ext;

    if (std.mem.eql(u8, rel, "index")) return allocator.dupe(u8, "/");

    var result = try allocator.alloc(u8, rel.len + 1);
    result[0] = '/';
    @memcpy(result[1..], rel);
    return result;
}

fn isHexChar(c: u8) bool {
    return (c >= '0' and c <= '9') or (c >= 'a' and c <= 'f') or (c >= 'A' and c <= 'F');
}

fn cleanGeneratedFiles(io: std.Io, allocator: std.mem.Allocator) !void {
    const cwd = std.Io.Dir.cwd();

    var app_dir = cwd.openDir(io, "src/app", .{ .iterate = true }) catch return;
    defer app_dir.close(io);

    var walker = try app_dir.walk(allocator);
    defer walker.deinit();

    var to_delete = std.ArrayList([]u8).empty;
    defer {
        for (to_delete.items) |p| allocator.free(p);
        to_delete.deinit(allocator);
    }

    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.path, ".zig")) continue;
        const p = try std.fmt.allocPrint(allocator, "src/app/{s}", .{entry.path});
        try to_delete.append(allocator, p);
    }

    for (to_delete.items) |p| {
        cwd.deleteFile(io, p) catch {};
    }
}

fn cmdDev(init: std.process.Init) !void {
    const io = init.io;
    const allocator = init.gpa;
    
    std.debug.print("🚀 Nuri development mode\n", .{});
    std.debug.print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n", .{});

    // Initial build (markdown → zig + routes.zig)
    try cmdBuild(init);

    std.debug.print("\n🌐 Compiling and starting server...\n", .{});
    std.debug.print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n", .{});
    std.debug.print("📁 Watching content/ and public/ directories for changes...\n", .{});
    std.debug.print("Press Ctrl+C to stop\n\n", .{});

    // Set up file watchers for both content and public directories
    var content_mtimes = std.StringHashMap(std.Io.Timestamp).init(allocator);
    defer {
        var it = content_mtimes.keyIterator();
        while (it.next()) |key| {
            allocator.free(key.*);
        }
        content_mtimes.deinit();
    }

    var public_mtimes = std.StringHashMap(std.Io.Timestamp).init(allocator);
    defer {
        var it = public_mtimes.keyIterator();
        while (it.next()) |key| {
            allocator.free(key.*);
        }
        public_mtimes.deinit();
    }

    try scanDirectoryWithExt(io, allocator, "content", ".md", &content_mtimes);
    try scanDirectoryWithExt(io, allocator, "public", null, &public_mtimes);

    // Server process (runs zig-out/bin/nuri-site directly)
    var server_child: ?std.process.Child = null;
    defer if (server_child) |*child| {
        child.kill(io);
    };

    // Compile the project
    const compileProject = struct {
        fn call(io_inner: std.Io) !void {
            std.debug.print("⏳ Compiling...\n", .{});
            var build_child = try std.process.spawn(io_inner, .{
                .argv = &[_][]const u8{ "zig", "build" },
                .stdin = .ignore,
                .stdout = .inherit,
                .stderr = .inherit,
            });
            const term = try build_child.wait(io_inner);
            if (term != .exited or term.exited != 0) {
                return error.CompileFailed;
            }
        }
    }.call;

    // Helper to (re)start the server binary
    const restartServer = struct {
        fn call(io_inner: std.Io, child: *?std.process.Child) !void {
            // Kill existing server if any (kill() reaps the child in zig 0.16)
            if (child.*) |*c| {
                std.debug.print("🔄 Stopping server...\n", .{});
                c.kill(io_inner);
                child.* = null;
            }

            // Run the compiled binary directly
            const argv = &[_][]const u8{ "zig-out/bin/nuri-site" };
            child.* = try std.process.spawn(io_inner, .{
                .argv = argv,
                .stdin = .ignore,
                .stdout = .inherit,
                .stderr = .inherit,
            });
            std.debug.print("✅ Server running at http://localhost:3000\n", .{});
        }
    }.call;

    // Initial compile + start
    try compileProject(io);
    try restartServer(io, &server_child);

    // Watch loop - runs until Ctrl+C
    while (true) {
        try std.Io.sleep(io, .fromNanoseconds(1_000_000_000), .awake);

        var current_content_mtimes = std.StringHashMap(std.Io.Timestamp).init(allocator);
        defer {
            var it = current_content_mtimes.keyIterator();
            while (it.next()) |key| {
                allocator.free(key.*);
            }
            current_content_mtimes.deinit();
        }

        var current_public_mtimes = std.StringHashMap(std.Io.Timestamp).init(allocator);
        defer {
            var it = current_public_mtimes.keyIterator();
            while (it.next()) |key| {
                allocator.free(key.*);
            }
            current_public_mtimes.deinit();
        }

        try scanDirectoryWithExt(io, allocator, "content", ".md", &current_content_mtimes);
        try scanDirectoryWithExt(io, allocator, "public", null, &current_public_mtimes);

        var content_changed = false;
        var public_changed = false;

        // Check content directory for changes
        var it = current_content_mtimes.iterator();
        while (it.next()) |entry| {
            const path = entry.key_ptr.*;
            const mtime = entry.value_ptr.*;

            const prev_mtime = content_mtimes.get(path);
            if (prev_mtime == null or !std.meta.eql(prev_mtime.?, mtime)) {
                content_changed = true;
                std.debug.print("📝 Content change: {s}\n", .{path});
            }
        }

        // Check for deleted content files
        var old_check = content_mtimes.iterator();
        while (old_check.next()) |entry| {
            if (!current_content_mtimes.contains(entry.key_ptr.*)) {
                content_changed = true;
                std.debug.print("🗑️  Content deleted: {s}\n", .{entry.key_ptr.*});
            }
        }

        // Check public directory for changes
        it = current_public_mtimes.iterator();
        while (it.next()) |entry| {
            const path = entry.key_ptr.*;
            const mtime = entry.value_ptr.*;

            const prev_mtime = public_mtimes.get(path);
            if (prev_mtime == null or !std.meta.eql(prev_mtime.?, mtime)) {
                public_changed = true;
                std.debug.print("🎨 Static file change: {s}\n", .{path});
            }
        }

        // Check for deleted public files
        old_check = public_mtimes.iterator();
        while (old_check.next()) |entry| {
            if (!current_public_mtimes.contains(entry.key_ptr.*)) {
                public_changed = true;
                std.debug.print("🗑️  Static file deleted: {s}\n", .{entry.key_ptr.*});
            }
        }

        // Handle content changes (full rebuild + restart)
        if (content_changed) {
            std.debug.print("🔄 Rebuilding markdown...\n", .{});
            cmdBuild(init) catch |err| {
                std.debug.print("❌ Build failed: {any}\n", .{err});
                continue;
            };
            
            compileProject(io) catch |err| {
                std.debug.print("❌ Compile failed: {any}\n", .{err});
                continue;
            };
            restartServer(io, &server_child) catch |err| {
                std.debug.print("❌ Server start failed: {any}\n", .{err});
                continue;
            };

            // Update content state
            var old_it = content_mtimes.keyIterator();
            while (old_it.next()) |key| {
                allocator.free(key.*);
            }
            content_mtimes.clearRetainingCapacity();

            var new_it = current_content_mtimes.iterator();
            while (new_it.next()) |entry| {
                const key_copy = try allocator.dupe(u8, entry.key_ptr.*);
                try content_mtimes.put(key_copy, entry.value_ptr.*);
            }
        }

        // Handle public changes (just restart to clear in-memory cache)
        if (public_changed) {
            std.debug.print("🔄 Restarting server to reload static files...\n", .{});
            restartServer(io, &server_child) catch |err| {
                std.debug.print("❌ Server restart failed: {any}\n", .{err});
                continue;
            };

            // Update public state
            var old_it = public_mtimes.keyIterator();
            while (old_it.next()) |key| {
                allocator.free(key.*);
            }
            public_mtimes.clearRetainingCapacity();

            var new_it = current_public_mtimes.iterator();
            while (new_it.next()) |entry| {
                const key_copy = try allocator.dupe(u8, entry.key_ptr.*);
                try public_mtimes.put(key_copy, entry.value_ptr.*);
            }
        }
    }
}

fn scanDirectory(io: std.Io, allocator: std.mem.Allocator, dir_path: []const u8, mtimes: *std.StringHashMap(std.Io.Timestamp)) !void {
    const cwd = std.Io.Dir.cwd();
    
    var dir = cwd.openDir(io, dir_path, .{ .iterate = true }) catch return;
    defer dir.close(io);

    var walker = try dir.walk(allocator);
    defer walker.deinit();

    while (walker.next(io) catch return) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.basename, ".md")) continue;

        const full_path = std.fs.path.join(allocator, &.{ dir_path, entry.path }) catch continue;
        defer allocator.free(full_path);
        
        const stat = cwd.statFile(io, full_path, .{}) catch continue;

        const key = allocator.dupe(u8, full_path) catch continue;
        mtimes.put(key, stat.mtime) catch {
            allocator.free(key);
            continue;
        };
    }
}

/// Scan directory for files, optionally filtering by extension (null = all files)
fn scanDirectoryWithExt(io: std.Io, allocator: std.mem.Allocator, dir_path: []const u8, extension: ?[]const u8, mtimes: *std.StringHashMap(std.Io.Timestamp)) !void {
    const cwd = std.Io.Dir.cwd();
    
    var dir = cwd.openDir(io, dir_path, .{ .iterate = true }) catch return;
    defer dir.close(io);

    var walker = try dir.walk(allocator);
    defer walker.deinit();

    while (walker.next(io) catch return) |entry| {
        if (entry.kind != .file) continue;
        
        // Filter by extension if specified
        if (extension) |ext| {
            if (!std.mem.endsWith(u8, entry.basename, ext)) continue;
        }

        const full_path = std.fs.path.join(allocator, &.{ dir_path, entry.path }) catch continue;
        defer allocator.free(full_path);
        
        const stat = cwd.statFile(io, full_path, .{}) catch continue;

        const key = allocator.dupe(u8, full_path) catch continue;
        mtimes.put(key, stat.mtime) catch {
            allocator.free(key);
            continue;
        };
    }
}
